(add-to-list 'auto-mode-alist '("\\.gdscript\\'" . zmd/generic-programming-mode))
(add-to-list 'auto-mode-alist '("\\.go\\'" . zmd/generic-programming-mode))
(add-to-list 'auto-mode-alist '("\\.rust\\'" . zmd/generic-programming-mode))
(add-to-list 'auto-mode-alist '("\\.scala\\'" . zmd/generic-programming-mode))
(add-to-list 'auto-mode-alist '("\\.sbt\\'" . zmd/generic-programming-mode))
(add-to-list 'auto-mode-alist '("\\.sc\\'" . zmd/generic-programming-mode))
