#!/bin/sh

destination="$HOME/wrk/screenshots/$(date +%Y)/$(date +%Y-%m-%d_%H\:%M\:%S_%Z).png"
mkdir -p "$(dirname "$destination")"

[ "$2" ] && sleep "$2"

case $1 in
  "everything")
    maim "$destination"
    ;;
  "window")
    maim -i $(xdotool getactivewindow) "$destination"
    ;;
  "selection")
    maim -s "$destination"
    ;;
esac
